# -*- coding: utf-8 -*-
"""Despliegue Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A6eh740riNT90BHGojGhk-DuvLgeNovx
"""

#Librerías
import numpy as np
import pandas as pd
import pickle

import streamlit as st
import numpy as np
import pandas as pd
import pickle

# Cargar modelo
import os
filename = os.path.join(os.path.dirname(__file__), 'modelo_final.pkl')
pipeline = pickle.load(open(filename, 'rb'))

st.title('Predicción de Enfermedad Cardíaca')
st.write('Ingrese los datos del paciente')

# Entradas
age = st.slider('Edad', min_value=18, max_value=100, value=50, step=1)
resting_bp = st.slider('Presión Arterial en Reposo (mm Hg)', min_value=80, max_value=200, value=120, step=1)
max_hr = st.slider('Frecuencia Cardíaca Máxima', min_value=60, max_value=220, value=150, step=1)
oldpeak = st.slider('Oldpeak', min_value=0.0, max_value=6.0, value=1.0, step=0.1)
fasting_bs = st.selectbox('Azúcar en Sangre en Ayunas > 120 mg/dl', ['No', 'Sí'])
sex = st.selectbox('Sexo', ['M', 'F'])
chest_pain = st.selectbox('Tipo de Dolor en el Pecho', ['ATA', 'NAP', 'ASY', 'TA'])
resting_ecg = st.selectbox('ECG en Reposo', ['Normal', 'ST', 'LVH'])
exercise_angina = st.selectbox('Angina por Ejercicio', ['N', 'Y'])
st_slope = st.selectbox('Pendiente ST', ['Up', 'Flat', 'Down'])

# DataFrame con datos crudos
datos = pd.DataFrame([[age, resting_bp, 1 if fasting_bs == 'Sí' else 0,
                       max_hr, oldpeak, sex, chest_pain,
                       resting_ecg, exercise_angina, st_slope]],
                     columns=['Age', 'RestingBP', 'FastingBS', 'MaxHR', 'Oldpeak',
                              'Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope'])

# Predicción
if st.button('Predecir'):
    prediccion = pipeline.predict(datos)[0]
    probabilidad = pipeline.predict_proba(datos)[0][1]

    if prediccion == 1:
        st.error(f' El paciente TIENE riesgo de enfermedad cardíaca')
    else:
        st.success(f' El paciente NO tiene riesgo de enfermedad cardíaca')

    st.info(f'Probabilidad de enfermedad: {probabilidad*100:.1f}%')

st.warning('El modelo tiene una precisión aproximada del 88%')
