# -*- coding: utf-8 -*-
"""Despliegue Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A6eh740riNT90BHGojGhk-DuvLgeNovx
"""

#Librerías
import streamlit as st
import numpy as np
import pandas as pd
import pickle
import os

# NECESARIO para cargar el pipeline
def preparar_datos(df):
    df = df.copy()
    
    df.loc[df['RestingBP'] == 0, 'RestingBP'] = np.nan
    df['RestingBP'] = df['RestingBP'].fillna(df['RestingBP'].median())
    
    if 'Cholesterol' in df.columns:
        df = df.drop(columns=['Cholesterol'])
    
    df = pd.get_dummies(df, columns=['Sex', 'ExerciseAngina'], drop_first=True, dtype=int)
    df = pd.get_dummies(df, columns=['ChestPainType', 'RestingECG', 'ST_Slope'], drop_first=False, dtype=int)
    
    if 'ST_Slope_Flat' in df.columns:
        df = df.drop(columns=['ST_Slope_Flat'])
    
    df['HR_Reserve'] = df['MaxHR'] - df['Age']
    df['AgeGroup'] = df['Age'].apply(lambda age: 0 if age < 45 else (1 if age < 60 else 2))
    df['BP_Category'] = df['RestingBP'].apply(lambda bp: 0 if bp < 120 else (1 if bp < 140 else 2)) if 'RestingBP' in df.columns else 0
    
    df = df.drop(columns=['Age', 'RestingBP'], errors='ignore')
    
    if 'HeartDisease' in df.columns:
        df = df.drop(columns=['HeartDisease'])
    
    return df

# Cargar modelo
filename = os.path.join(os.path.dirname(__file__), 'modelo_final.pkl')
pipeline = pickle.load(open(filename, 'rb'))

st.title('Predicción de Enfermedad Cardíaca')
st.write('Ingrese los datos del paciente')

# Entradas
age = st.slider('Edad', min_value=18, max_value=100, value=50, step=1)
resting_bp = st.slider('Presión Arterial en Reposo (mm Hg)', min_value=80, max_value=200, value=120, step=1)
max_hr = st.slider('Frecuencia Cardíaca Máxima', min_value=60, max_value=220, value=150, step=1)
oldpeak = st.slider('Oldpeak', min_value=0.0, max_value=6.0, value=1.0, step=0.1)
fasting_bs = st.selectbox('Azúcar en Sangre en Ayunas > 120 mg/dl', ['No', 'Sí'])
sex = st.selectbox('Sexo', ['M', 'F'])
chest_pain = st.selectbox('Tipo de Dolor en el Pecho', ['ATA', 'NAP', 'ASY', 'TA'])
resting_ecg = st.selectbox('ECG en Reposo', ['Normal', 'ST', 'LVH'])
exercise_angina = st.selectbox('Angina por Ejercicio', ['N', 'Y'])
st_slope = st.selectbox('Pendiente ST', ['Up', 'Flat', 'Down'])

# DataFrame con datos crudos
datos = pd.DataFrame([[age, resting_bp, 1 if fasting_bs == 'Sí' else 0,
                       max_hr, oldpeak, sex, chest_pain,
                       resting_ecg, exercise_angina, st_slope]],
                     columns=['Age', 'RestingBP', 'FastingBS', 'MaxHR', 'Oldpeak',
                              'Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope'])

# Predicción
if st.button('Predecir'):
    # Preparación manual
    sex_m = 1 if sex == 'M' else 0
    exercise_angina_y = 1 if exercise_angina == 'Y' else 0
    chest_asy = 1 if chest_pain == 'ASY' else 0
    chest_ata = 1 if chest_pain == 'ATA' else 0
    chest_nap = 1 if chest_pain == 'NAP' else 0
    chest_ta = 1 if chest_pain == 'TA' else 0
    ecg_lvh = 1 if resting_ecg == 'LVH' else 0
    ecg_normal = 1 if resting_ecg == 'Normal' else 0
    ecg_st = 1 if resting_ecg == 'ST' else 0
    slope_down = 1 if st_slope == 'Down' else 0
    slope_up = 1 if st_slope == 'Up' else 0
    hr_reserve = max_hr - age
    age_group = 0 if age < 45 else (1 if age < 60 else 2)
    bp_category = 0 if resting_bp < 120 else (1 if resting_bp < 140 else 2)
    fasting = 1 if fasting_bs == 'Sí' else 0

    datos = pd.DataFrame([[fasting, max_hr, oldpeak, sex_m, exercise_angina_y,
                           chest_asy, chest_ata, chest_nap, chest_ta,
                           ecg_lvh, ecg_normal, ecg_st, slope_down, slope_up,
                           hr_reserve, age_group, bp_category]],
                         columns=['FastingBS', 'MaxHR', 'Oldpeak', 'Sex_M', 'ExerciseAngina_Y',
                                  'ChestPainType_ASY', 'ChestPainType_ATA', 'ChestPainType_NAP',
                                  'ChestPainType_TA', 'RestingECG_LVH', 'RestingECG_Normal',
                                  'RestingECG_ST', 'ST_Slope_Down', 'ST_Slope_Up',
                                  'HR_Reserve', 'AgeGroup', 'BP_Category'])

    prediccion = pipeline.named_steps['modelo'].predict(datos)[0]
    probabilidad = pipeline.named_steps['modelo'].predict_proba(datos)[0][1]

    if prediccion == 1:
        st.error('⚠️ El paciente TIENE riesgo de enfermedad cardíaca')
    else:
        st.success('✅ El paciente NO tiene riesgo de enfermedad cardíaca')
    
    st.info(f'Probabilidad de enfermedad: {probabilidad*100:.1f}%')
