# -*- coding: utf-8 -*-
"""heartFinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kyCqgF9IYkRJwTu5sU18u5sTvCW4AURN
"""

#Librerias necesarias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer
from imblearn.over_sampling import SMOTE
import warnings
warnings.filterwarnings('ignore')

# Configurar estilos
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (12, 6)

print("✓ Librerías importadas correctamente")

df = pd.read_csv("/content/heart.csv")
df.head()

print("="*80)
print("EXPLORACIÓN INICIAL - CORAZÓN")
print("="*80)

print(f"\n1. DIMENSIONES:")
print(f"   Registros: {len(df):,}")
print(f"   Columnas: {len(df.columns)}")

print(f"\n2. INFORMACIÓN DE TIPOS:")
print(df.dtypes)

print(f"\n3. VALORES FALTANTES:")
nulos = df.isnull().sum()
print(nulos[nulos > 0])

print(f"\n4. NOMBRES DE COLUMNAS:")
for i, col in enumerate(df.columns, 1):
    print(f"   {i:2d}. {col}")

df.info()

for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].astype('category')

print("✓ Columnas de tipo 'object' convertidas a 'category' correctamente.")
df.info()

df.head()

df["ID"] = range(1, len(df)+1)

ids = df['ID'].value_counts()
ids[ids>1]

"""# 2.Eliminar variables irrelevantes"""

df = df.drop('ID',axis=1) #Eliminamos el ID por ser irrelevante, axis=1 indica que es una columna
df.head()

"""# 3.Descripción estadística

Vbles numéricas
"""

df.describe()

df.hist()

df.plot.box()
#Hay que hacer normalización por la gran diferencia en las unidades

filtered_df = df[(df['Cholesterol'] == 0) | (df['RestingBP'] == 0) | (df['RestingBP'] > 400)]
print("Filas con Colesterol = 0, RestingBP = 0, o RestingBP > 400:")
print(filtered_df)

plt.figure(figsize=(14, 6))

# Scatter plot for RestingBP vs HeartDisease
plt.subplot(1, 2, 1)
sns.scatterplot(data=df, x='RestingBP', y='HeartDisease', hue='HeartDisease', palette='viridis', alpha=0.7)
plt.title('Presión Arterial en Reposo vs Enfermedad Cardiaca')
plt.xlabel('Presión Arterial en Reposo')
plt.ylabel('Enfermedad Cardiaca')
plt.yticks([0, 1], ['No Disease', 'Disease'])

# Scatter plot for Cholesterol vs HeartDisease
plt.subplot(1, 2, 2)
sns.scatterplot(data=df, x='Cholesterol', y='HeartDisease', hue='HeartDisease', palette='viridis', alpha=0.7)
plt.title('Colesterol vs Enfermedad Cardiaca')
plt.xlabel('Colesterol')
plt.ylabel('Enfermedad Cardiaca')
plt.yticks([0, 1], ['No Disease', 'Disease'])

plt.tight_layout()
plt.show()



"""Vbles categóricas"""

df.describe(include='category')

categorical_cols = df.select_dtypes(include='category').columns

plt.figure(figsize=(15, 10))
for i, col in enumerate(categorical_cols):
    plt.subplot(2, 3, i + 1)
    sns.countplot(data=df, x=col, palette='viridis')
    plt.title(f'Distribución de {col}')
    plt.xlabel(col)
    plt.ylabel('Conteo')
    plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
sns.countplot(data=df, x='Sex', hue='HeartDisease', palette='coolwarm')
plt.title('HeartDisease por Sexo')
plt.xlabel('Sexo')
plt.ylabel('Conteo')

plt.subplot(1, 3, 2)
sns.countplot(data=df, x='ChestPainType', hue='HeartDisease', palette='coolwarm')
plt.title('HeartDisease por Tipo de Dolor en el Pecho')
plt.xlabel('Tipo de Dolor en el Pecho')
plt.ylabel('Conteo')
plt.xticks(rotation=45, ha='right')

plt.subplot(1, 3, 3)
sns.countplot(data=df, x='ST_Slope', hue='HeartDisease', palette='coolwarm')
plt.title('HeartDisease por Pendiente del Segmento ST')
plt.xlabel('Pendiente del Segmento ST')
plt.ylabel('Conteo')
plt.xticks(rotation=45, ha='right')

plt.tight_layout()
plt.show()

"""### Scatter Plots de Variables Numéricas"""

plt.figure(figsize=(18, 6))

# Scatter plot: Age vs Cholesterol, colored by HeartDisease
plt.subplot(1, 3, 1)
sns.scatterplot(data=df, x='Age', y='Cholesterol', hue='HeartDisease', palette='viridis', alpha=0.7)
plt.title('Edad vs Colesterol por Enfermedad Cardiaca')
plt.xlabel('Edad')
plt.ylabel('Colesterol')

# Scatter plot: RestingBP vs MaxHR, colored by HeartDisease
plt.subplot(1, 3, 2)
sns.scatterplot(data=df, x='RestingBP', y='MaxHR', hue='HeartDisease', palette='viridis', alpha=0.7)
plt.title('Presión Arterial en Reposo vs Frecuencia Cardiaca Máxima por Enfermedad Cardiaca')
plt.xlabel('Presión Arterial en Reposo')
plt.ylabel('Frecuencia Cardiaca Máxima')

# Scatter plot: Age vs MaxHR, colored by HeartDisease
plt.subplot(1, 3, 3)
sns.scatterplot(data=df, x='Age', y='MaxHR', hue='HeartDisease', palette='viridis', alpha=0.7)
plt.title('Edad vs Frecuencia Cardiaca Máxima por Enfermedad Cardiaca')
plt.xlabel('Edad')
plt.ylabel('Frecuencia Cardiaca Máxima')

plt.tight_layout()
plt.show()

!pip install ydata-profiling
from ydata_profiling import ProfileReport

profile_data=ProfileReport(df, minimal=False) # minimal=True
profile_data
#Las variables que sean tipo object no salen en el ydataprofiling

profile_data.to_file(output_file="output.html")

"""# 4. Limpieza de datos atípicos o errores"""

print("LIMPIEZA: Cholesterol y RestingBP\n")

# Contar antes
print("ANTES:")
print(f"  Cholesterol ceros: {(df['Cholesterol'] == 0).sum()}")
print(f"  RestingBP ceros: {(df['RestingBP'] == 0).sum()}\n")

# Convertir ceros a NaN
df.loc[df['Cholesterol'] == 0, 'Cholesterol'] = np.nan
df.loc[df['RestingBP'] == 0, 'RestingBP'] = np.nan

(df['Cholesterol'].isnull().sum() / len(df)) * 100

df = df.drop(columns=['Cholesterol'])

# Imputar con mediana
mediana_rbp = df['RestingBP'].median()

df['RestingBP'].fillna(mediana_rbp, inplace=True)

# Resultados
print("DESPUÉS:")
print(f"  RestingBP imputados: {mediana_rbp:.2f} mm Hg")
print(f"  Nulos totales: {df.isnull().sum().sum()}\n")
print("✓ Limpieza completada")

df.head()

"""# Correlaciones para redundancias"""

# Todas las variables deben ser numéricas para calcular las correlaciones
# Se crean dummies para las variables categóricas
df = pd.get_dummies(df, columns=['Sex','ExerciseAngina'], drop_first=True, dtype=int)
df = pd.get_dummies(df, columns=['ChestPainType','RestingECG','ST_Slope',], drop_first=False, dtype=int)
df.head()

#Correlaciones
correlaciones=df.corr()
correlaciones

import seaborn as sns
plt.figure(figsize=(10,10))
sns.heatmap(df.corr(),annot=True)

df = df.drop(columns=['ST_Slope_Flat'])

#Correlaciones con la variable de objetivo
cor_variable_obj=correlaciones.loc['HeartDisease']

# Filter cor_variable_obj to only include columns present in df_num
cor_variable_obj = cor_variable_obj[df.columns]

cor_variable_obj

plt.figure(figsize=(6, 8))
plt.barh(y = df.columns, width=cor_variable_obj)

"""### Distribución de la variable objetivo: HeartDisease"""

plt.figure(figsize=(7, 5))
sns.countplot(data=df, x='HeartDisease', palette='viridis')
plt.title('Distribución de Enfermedad Cardíaca')
plt.xlabel('Enfermedad Cardíaca (0: No, 1: Sí)')
plt.ylabel('Conteo')
plt.xticks([0, 1], ['No Enfermedad', 'Enfermedad'])
plt.show()

"""# Ingeniería de características"""

# 1. Reserva de Frecuencia Cardíaca (sentido clínico: capacidad cardiovascular)
df['HR_Reserve'] = df['MaxHR'] - df['Age']

# 2. Grupo de edad
def categorize_age(age):
    if age < 45:
        return 0  # Adultos Jovenes
    elif age < 60:
        return 1  # Adultos
    else:
        return 2  # Adultos Mayores

df['AgeGroup'] = df['Age'].apply(categorize_age)

# 3. Categoría de presión arterial
def categorize_bp(bp):
    if bp < 120:
        return 0  # Normal
    elif bp < 140:
        return 1  # Elevada
    else:
        return 2  # Alta

df['BP_Category'] = df['RestingBP'].apply(categorize_bp)

print("✓ Nuevas variables creadas:")
print(df[['HR_Reserve', 'AgeGroup', 'BP_Category']].head())
print(f"\nShape final: {df.shape}")

print(df.columns.tolist())

df = df.drop(columns=['Age', 'RestingBP'])
df.head()

from sklearn.model_selection import train_test_split

X = df.drop(columns=['HeartDisease'])
y = df['HeartDisease']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

print(f"X_train: {X_train.shape}")
print(f"X_test:  {X_test.shape}")
print(f"\nDistribución train: {y_train.value_counts().to_dict()}")
print(f"Distribución test:  {y_test.value_counts().to_dict()}")

fig, axes = plt.subplots(1, 2, figsize=(12, 5))

# Train
axes[0].bar(['No Enfermedad (0)', 'Enfermedad (1)'],
            y_train.value_counts().sort_index(),
            color=['steelblue', 'tomato'])
axes[0].set_title('Distribución Train (70%)')
axes[0].set_ylabel('Conteo')
for i, v in enumerate(y_train.value_counts().sort_index()):
    axes[0].text(i, v + 2, str(v), ha='center', fontweight='bold')

# Test
axes[1].bar(['No Enfermedad (0)', 'Enfermedad (1)'],
            y_test.value_counts().sort_index(),
            color=['steelblue', 'tomato'])
axes[1].set_title('Distribución Test (30%)')
axes[1].set_ylabel('Conteo')
for i, v in enumerate(y_test.value_counts().sort_index()):
    axes[1].text(i, v + 2, str(v), ha='center', fontweight='bold')

plt.suptitle('Distribución de la Variable Objetivo', fontweight='bold')
plt.tight_layout()
plt.show()

import pickle

X_train.to_csv('X_train.csv', index=False)
X_test.to_csv('X_test.csv', index=False)
y_train.to_csv('y_train.csv', index=False)
y_test.to_csv('y_test.csv', index=False)

print("✓ Datos guardados correctamente")
print(f"  X_train: {X_train.shape}")
print(f"  X_test:  {X_test.shape}")