# -*- coding: utf-8 -*-
"""Modelos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SP1lw4Gq0TgkgD-l2sNJe-QcBe6P0rE1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import KFold, cross_val_score, cross_validate
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                             f1_score, roc_auc_score, confusion_matrix,
                             classification_report, roc_curve, auc)
import pickle
import warnings
warnings.filterwarnings('ignore')



# Cargar los datos de entrenamiento y prueba
X_train = pd.read_csv('X_train.csv')
y_train = pd.read_csv('y_train.csv').squeeze()

X_test = pd.read_csv('X_test.csv')
y_test = pd.read_csv('y_test.csv').squeeze()

print("✓ Datos cargados correctamente\n")

# Verificar dimensiones
print(f"X_train: {X_train.shape}")
print(f"y_train: {y_train.shape}")
print(f"X_test: {X_test.shape}")
print(f"y_test: {y_test.shape}")

# Verificar balance de clases
print(f"\nBalance en y_train:")
print(y_train.value_counts(normalize=True))

print(f"\nBalance en y_test:")
print(y_test.value_counts(normalize=True))

# Mostrar nombre de características
print(f"\nCaracterísticas ({len(X_train.columns)}):")
print(X_train.columns.tolist())

# Definir KFold con 10 splits
kfold = KFold(n_splits=10, shuffle=True, random_state=42)

print("="*80)
print("CONFIGURACIÓN DE VALIDACIÓN CRUZADA")
print("="*80)
print(f"  • Tipo: K-Fold")
print(f"  • Número de folds: 10")
print(f"  • Shuffle: Sí")
print(f"  • Random state: 42")
print(f"\nCada fold tendrá aproximadamente {len(X_train) // 10} muestras para entrenamiento")
print(f"y aproximadamente {len(X_train) // 10} para validación")

def entrenar_con_cv(modelo, nombre_modelo, X_train, y_train, X_test, y_test):
    """
    Entrena un modelo con validación cruzada 10-fold y evalúa en test set
    """

    print(f"\n{'='*90}")
    print(f"ENTRENANDO: {nombre_modelo}")
    print(f"{'='*90}")

    # PASO 1: VALIDACIÓN CRUZADA EN X_train
    scoring = {
        'accuracy': 'accuracy',
        'precision': 'precision',
        'recall': 'recall',
        'f1': 'f1',
        'roc_auc': 'roc_auc'
    }

    cv_results = cross_validate(modelo, X_train, y_train, cv=kfold,
                                scoring=scoring, return_train_score=False)

    # PASO 2: MOSTRAR RESULTADOS POR FOLD
    print(f"\nResultados por Fold (Validación Cruzada - 10 Folds):")
    print(f"{'Fold':<6} {'Accuracy':<12} {'Precision':<12} {'Recall':<12} {'F1':<12} {'AUC':<12}")
    print(f"{'-'*66}")

    for fold in range(10):
        acc = cv_results['test_accuracy'][fold]
        prec = cv_results['test_precision'][fold]
        rec = cv_results['test_recall'][fold]
        f1 = cv_results['test_f1'][fold]
        auc = cv_results['test_roc_auc'][fold]
        print(f"{fold+1:<6} {acc:<12.4f} {prec:<12.4f} {rec:<12.4f} {f1:<12.4f} {auc:<12.4f}")

    # PASO 3: ESTADÍSTICAS DE VALIDACIÓN CRUZADA
    print(f"\n{'PROMEDIO':<6} {cv_results['test_accuracy'].mean():<12.4f} " +
          f"{cv_results['test_precision'].mean():<12.4f} " +
          f"{cv_results['test_recall'].mean():<12.4f} " +
          f"{cv_results['test_f1'].mean():<12.4f} " +
          f"{cv_results['test_roc_auc'].mean():<12.4f}")

    print(f"\nDesviación Estándar (Variabilidad entre folds):")
    print(f"  • Accuracy:  ±{cv_results['test_accuracy'].std():.4f}")
    print(f"  • Precision: ±{cv_results['test_precision'].std():.4f}")
    print(f"  • Recall:    ±{cv_results['test_recall'].std():.4f}")
    print(f"  • F1:        ±{cv_results['test_f1'].std():.4f}")
    print(f"  • AUC-ROC:   ±{cv_results['test_roc_auc'].std():.4f}")

    # PASO 4: ENTRENAR EN TODO X_train
    print(f"\n→ Entrenando en TODO X_train para evaluación final en X_test...")
    modelo.fit(X_train, y_train)

    # PASO 5: EVALUACIÓN EN X_test
    y_pred = modelo.predict(X_test)
    y_pred_proba = modelo.predict_proba(X_test)[:, 1] if hasattr(modelo, 'predict_proba') else None

    test_acc = accuracy_score(y_test, y_pred)
    test_prec = precision_score(y_test, y_pred)
    test_rec = recall_score(y_test, y_pred)
    test_f1 = f1_score(y_test, y_pred)
    test_auc = roc_auc_score(y_test, y_pred_proba) if y_pred_proba is not None else None

    print(f"\n{'EVALUACIÓN EN X_TEST':<30}")
    print(f"  • Accuracy:  {test_acc:.4f}")
    print(f"  • Precision: {test_prec:.4f}")
    print(f"  • Recall:    {test_rec:.4f}")
    print(f"  • F1-Score:  {test_f1:.4f}")
    if test_auc:
        print(f"  • AUC-ROC:   {test_auc:.4f}")

    # PASO 6: GUARDAR RESULTADOS
    resultados = {
        'nombre': nombre_modelo,
        'modelo': modelo,
        'cv_accuracy_mean': cv_results['test_accuracy'].mean(),
        'cv_accuracy_std': cv_results['test_accuracy'].std(),
        'cv_precision_mean': cv_results['test_precision'].mean(),
        'cv_recall_mean': cv_results['test_recall'].mean(),
        'cv_f1_mean': cv_results['test_f1'].mean(),
        'cv_f1_std': cv_results['test_f1'].std(),
        'cv_auc_mean': cv_results['test_roc_auc'].mean(),
        'test_accuracy': test_acc,
        'test_precision': test_prec,
        'test_recall': test_rec,
        'test_f1': test_f1,
        'test_auc': test_auc,
        'y_pred': y_pred,
        'y_pred_proba': y_pred_proba,
        'cv_results': cv_results
    }

    return resultados

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

# Lista para almacenar resultados
modelos_resultados = []

print("\n" + "="*90)
print("INICIANDO ENTRENAMIENTO DE MODELOS SUPERVISADOS")
print("="*90)

# ─────────────────────────────────────────────────────────────────────────
# MODELO 1: REGRESIÓN LOGÍSTICA (con normalización)
# ─────────────────────────────────────────────────────────────────────────
modelo_lr = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LogisticRegression(random_state=42, max_iter=1000))
])
resultado_lr = entrenar_con_cv(modelo_lr, "1. Regresión Logística",
                               X_train, y_train, X_test, y_test)
modelos_resultados.append(resultado_lr)

# ─────────────────────────────────────────────────────────────────────────
# MODELO 2: ÁRBOL DE DECISIÓN (sin normalización)
# ─────────────────────────────────────────────────────────────────────────
modelo_dt = DecisionTreeClassifier(random_state=42, max_depth=10)
resultado_dt = entrenar_con_cv(modelo_dt, "2. Árbol de Decisión",
                               X_train, y_train, X_test, y_test)
modelos_resultados.append(resultado_dt)

# ─────────────────────────────────────────────────────────────────────────
# MODELO 3: SVM (con normalización)
# ─────────────────────────────────────────────────────────────────────────
modelo_svm = Pipeline([
    ('scaler', StandardScaler()),
    ('model', SVC(kernel='rbf', probability=True, random_state=42))
])
resultado_svm = entrenar_con_cv(modelo_svm, "3. Support Vector Machine (SVM)",
                                X_train, y_train, X_test, y_test)
modelos_resultados.append(resultado_svm)

# ─────────────────────────────────────────────────────────────────────────
# MODELO 4: KNN (con normalización)
# ─────────────────────────────────────────────────────────────────────────
modelo_knn = Pipeline([
    ('scaler', StandardScaler()),
    ('model', KNeighborsClassifier(n_neighbors=5))
])
resultado_knn = entrenar_con_cv(modelo_knn, "4. K-Nearest Neighbors (KNN)",
                                X_train, y_train, X_test, y_test)
modelos_resultados.append(resultado_knn)

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier

print("\n" + "="*90)
print("INICIANDO ENTRENAMIENTO DE MODELOS DE ENSAMBLE")
print("="*90)

# ─────────────────────────────────────────────────────────────────────────
# ENSAMBLE 1: RANDOM FOREST
# ─────────────────────────────────────────────────────────────────────────
modelo_rf = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
resultado_rf = entrenar_con_cv(modelo_rf, "5. Random Forest",
                               X_train, y_train, X_test, y_test)
modelos_resultados.append(resultado_rf)

# ─────────────────────────────────────────────────────────────────────────
# ENSAMBLE 2: XGBOOST
# ─────────────────────────────────────────────────────────────────────────
modelo_xgb = XGBClassifier(random_state=42, eval_metric='logloss', n_jobs=-1)
resultado_xgb = entrenar_con_cv(modelo_xgb, "6. XGBoost",
                                X_train, y_train, X_test, y_test)
modelos_resultados.append(resultado_xgb)

# ─────────────────────────────────────────────────────────────────────────
# ENSAMBLE 3: GRADIENT BOOSTING
# ─────────────────────────────────────────────────────────────────────────
modelo_gb = GradientBoostingClassifier(n_estimators=100, random_state=42)
resultado_gb = entrenar_con_cv(modelo_gb, "7. Gradient Boosting",
                               X_train, y_train, X_test, y_test)
modelos_resultados.append(resultado_gb)

# Crear DataFrame con resultados
df_comparacion = pd.DataFrame({
    'Modelo': [r['nombre'] for r in modelos_resultados],
    'CV Accuracy': [r['cv_accuracy_mean'] for r in modelos_resultados],
    'CV ±': [r['cv_accuracy_std'] for r in modelos_resultados],
    'Test Accuracy': [r['test_accuracy'] for r in modelos_resultados],
    'Test Precision': [r['test_precision'] for r in modelos_resultados],
    'Test Recall': [r['test_recall'] for r in modelos_resultados],
    'Test F1': [r['test_f1'] for r in modelos_resultados],
    'Test AUC': [r['test_auc'] for r in modelos_resultados],
})

print("\n" + "="*90)
print("TABLA COMPARATIVA: RESULTADOS DE TODOS LOS MODELOS")
print("="*90)
print(df_comparacion.to_string(index=False))

# Ordenar por Test Accuracy
df_comparacion_sorted = df_comparacion.sort_values('Test Accuracy', ascending=False)

print("\n" + "="*90)
print("RANKING: MEJORES MODELOS (por Test Accuracy)")
print("="*90)
for idx, row in df_comparacion_sorted.iterrows():
    print(f"{idx+1}. {row['Modelo']:<35} Accuracy: {row['Test Accuracy']:.4f}")

# Visualizar comparación
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Gráfico 1: CV Accuracy vs Test Accuracy
ax1 = axes[0, 0]
x_pos = np.arange(len(df_comparacion))
ax1.bar(x_pos - 0.2, df_comparacion['CV Accuracy'], 0.4, label='CV Accuracy', alpha=0.8)
ax1.bar(x_pos + 0.2, df_comparacion['Test Accuracy'], 0.4, label='Test Accuracy', alpha=0.8)
ax1.set_ylabel('Accuracy')
ax1.set_title('CV vs Test Accuracy por Modelo')
ax1.set_xticks(x_pos)
ax1.set_xticklabels(df_comparacion['Modelo'], rotation=45, ha='right', fontsize=8)
ax1.legend()
ax1.grid(axis='y', alpha=0.3)

# Gráfico 2: F1-Score
ax2 = axes[0, 1]
ax2.bar(x_pos, df_comparacion['Test F1'], alpha=0.8, color='orange')
ax2.set_ylabel('F1-Score')
ax2.set_title('F1-Score por Modelo')
ax2.set_xticks(x_pos)
ax2.set_xticklabels(df_comparacion['Modelo'], rotation=45, ha='right', fontsize=8)
ax2.grid(axis='y', alpha=0.3)

# Gráfico 3: Precision vs Recall
ax3 = axes[1, 0]
ax3.bar(x_pos - 0.2, df_comparacion['Test Precision'], 0.4, label='Precision', alpha=0.8)
ax3.bar(x_pos + 0.2, df_comparacion['Test Recall'], 0.4, label='Recall', alpha=0.8)
ax3.set_ylabel('Score')
ax3.set_title('Precision vs Recall por Modelo')
ax3.set_xticks(x_pos)
ax3.set_xticklabels(df_comparacion['Modelo'], rotation=45, ha='right', fontsize=8)
ax3.legend()
ax3.grid(axis='y', alpha=0.3)

# Gráfico 4: AUC-ROC
ax4 = axes[1, 1]
ax4.bar(x_pos, df_comparacion['Test AUC'].fillna(0), alpha=0.8, color='green')
ax4.set_ylabel('AUC-ROC')
ax4.set_title('AUC-ROC por Modelo')
ax4.set_xticks(x_pos)
ax4.set_xticklabels(df_comparacion['Modelo'], rotation=45, ha='right', fontsize=8)
ax4.grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.savefig('01_comparacion_modelos.png', dpi=300, bbox_inches='tight')
plt.show()

print("\n✓ Gráfico guardado: 01_comparacion_modelos.png")

"""# ANOVA y Tukey"""

from scipy import stats
from statsmodels.stats.multicomp import pairwise_tukeyhsd
import numpy as np

print("\n" + "="*90)
print("ANÁLISIS ESTADÍSTICO: ANOVA + TUKEY")
print("="*90)

# Extraer los scores de accuracy de cada fold por modelo
scores_por_modelo = {
    r['nombre']: r['cv_results']['test_f1']
    for r in modelos_resultados
}

# ─────────────────────────────────────────────────────────────────────────
# ANOVA
# ─────────────────────────────────────────────────────────────────────────
f_stat, p_value = stats.f_oneway(*scores_por_modelo.values())

print(f"\nANOVA de un factor:")
print(f"  • F-estadístico: {f_stat:.4f}")
print(f"  • P-valor:       {p_value:.4f}")

if p_value < 0.05:
    print(f"\n✓ Hay diferencias estadísticamente significativas entre los modelos (p < 0.05)")
    print(f"  → Se procede con Tukey para identificar cuáles difieren")
else:
    print(f"\n⚠ No hay diferencias estadísticamente significativas (p >= 0.05)")

# ─────────────────────────────────────────────────────────────────────────
# TUKEY
# ─────────────────────────────────────────────────────────────────────────
print(f"\nPrueba de Tukey HSD:")

# Preparar datos para Tukey
scores_todos = []
nombres_todos = []
for nombre, scores in scores_por_modelo.items():
    scores_todos.extend(scores)
    nombres_todos.extend([nombre] * len(scores))

tukey = pairwise_tukeyhsd(scores_todos, nombres_todos, alpha=0.05)
print(tukey)

# ─────────────────────────────────────────────────────────────────────────
# SELECCIONAR LOS 3 MEJORES
# ─────────────────────────────────────────────────────────────────────────
print(f"\n{'='*90}")
print(f"TOP 3 MODELOS SELECCIONADOS PARA HIPERPARAMETRIZACIÓN")
print(f"{'='*90}")

df_ranking = pd.DataFrame({
    'Modelo': [r['nombre'] for r in modelos_resultados],
    'CV F1 media': [r['cv_f1_mean'] for r in modelos_resultados],
    'CV ±': [r['cv_f1_std'] for r in modelos_resultados],
    'Test F1': [r['test_f1'] for r in modelos_resultados],
    'Test AUC': [r['test_auc'] for r in modelos_resultados],
}).sort_values('CV F1 media', ascending=False)

top3 = df_ranking.head(3)
print(top3.to_string(index=False))

"""#Gridsearch"""

from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, f1_score

print("\n" + "="*90)
print("HIPERPARAMETRIZACIÓN - GRIDSEARCHCV")
print("="*90)

# ─────────────────────────────────────────────────────────────────────────
# GRADIENT BOOSTING
# ─────────────────────────────────────────────────────────────────────────
print("\n→ GridSearchCV: Gradient Boosting...")

param_grid_gb = {
    'n_estimators': [50, 100, 200],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.1, 0.3]
}

grid_gb = GridSearchCV(modelo_gb, param_grid_gb, cv=kfold,
                       scoring='f1', n_jobs=-1)
grid_gb.fit(X_train, y_train)

y_pred_gb = grid_gb.best_estimator_.predict(X_test)
print(f"  • Mejores parámetros: {grid_gb.best_params_}")
print(f"  • Mejor F1 (CV):      {grid_gb.best_score_:.4f}")
print(f"  • F1 Test:            {f1_score(y_test, y_pred_gb):.4f}")
print(f"  • Accuracy Test:      {accuracy_score(y_test, y_pred_gb):.4f}")

# ─────────────────────────────────────────────────────────────────────────
# SVM
# ─────────────────────────────────────────────────────────────────────────
print("\n→ GridSearchCV: SVM...")

param_grid_svm = {
    'model__C': [0.1, 1, 10, 100],
    'model__gamma': ['scale', 'auto']
}

grid_svm = GridSearchCV(modelo_svm, param_grid_svm, cv=kfold,
                        scoring='f1', n_jobs=-1)
grid_svm.fit(X_train, y_train)

y_pred_svm = grid_svm.best_estimator_.predict(X_test)
print(f"  • Mejores parámetros: {grid_svm.best_params_}")
print(f"  • Mejor F1 (CV):      {grid_svm.best_score_:.4f}")
print(f"  • F1 Test:            {f1_score(y_test, y_pred_svm):.4f}")
print(f"  • Accuracy Test:      {accuracy_score(y_test, y_pred_svm):.4f}")

# ─────────────────────────────────────────────────────────────────────────
# REGRESIÓN LOGÍSTICA
# ─────────────────────────────────────────────────────────────────────────
print("\n→ GridSearchCV: Regresión Logística...")

param_grid_lr = {
    'model__C': [0.01, 0.1, 1, 10, 100],
    'model__solver': ['lbfgs', 'liblinear']
}

grid_lr = GridSearchCV(modelo_lr, param_grid_lr, cv=kfold,
                       scoring='f1', n_jobs=-1)
grid_lr.fit(X_train, y_train)

y_pred_lr = grid_lr.best_estimator_.predict(X_test)
print(f"  • Mejores parámetros: {grid_lr.best_params_}")
print(f"  • Mejor F1 (CV):      {grid_lr.best_score_:.4f}")
print(f"  • F1 Test:            {f1_score(y_test, y_pred_lr):.4f}")
print(f"  • Accuracy Test:      {accuracy_score(y_test, y_pred_lr):.4f}")

# ─────────────────────────────────────────────────────────────────────────
# COMPARATIVA
# ─────────────────────────────────────────────────────────────────────────
print("\n" + "="*90)
print("COMPARATIVA GRIDSEARCHCV")
print("="*90)

df_grid = pd.DataFrame({
    'Modelo': ['Gradient Boosting', 'SVM', 'Regresión Logística'],
    'Mejores Parámetros': [grid_gb.best_params_, grid_svm.best_params_, grid_lr.best_params_],
    'Mejor F1 CV': [grid_gb.best_score_, grid_svm.best_score_, grid_lr.best_score_],
    'F1 Test': [f1_score(y_test, y_pred_gb), f1_score(y_test, y_pred_svm), f1_score(y_test, y_pred_lr)],
    'Accuracy Test': [accuracy_score(y_test, y_pred_gb), accuracy_score(y_test, y_pred_svm), accuracy_score(y_test, y_pred_lr)]
}).sort_values('F1 Test', ascending=False)

print(df_grid.to_string(index=False))

"""#Optimización Bayesiana"""

pip install scikit-optimize

from skopt.space import Integer, Real, Categorical
from skopt import BayesSearchCV

optimizer_kwargs = {
    'base_estimator': 'GP',
    'acq_func': 'EI',
}


# Gradient Boosting
space_gb = {
    'n_estimators': Integer(50, 200),
    'max_depth': Integer(3, 10),
    'learning_rate': Real(0.001, 0.5, prior='log-uniform'),
    'subsample': Real(0.5, 1.0),
}

# Regresión Logística
space_lr = {
    'model__C': Real(0.001, 100, prior='log-uniform'),
    'model__solver': Categorical(['lbfgs', 'liblinear'])
}

# SVM
space_svm = {
    'model__C': Real(0.1, 1000, prior='log-uniform'),
    'model__kernel': Categorical(['rbf', 'poly']),
    'model__gamma': Real(0.0001, 1, prior='log-uniform'),
}

print("\n" + "="*90)
print("OPTIMIZACIÓN BAYESIANA - BayesSearchCV")
print("="*90)

# Gradient Boosting
print("\n→ Bayesiana: Gradient Boosting...")
bayes_gb = BayesSearchCV(modelo_gb, space_gb, cv=kfold, scoring='f1',
                         n_iter=20, optimizer_kwargs=optimizer_kwargs,
                         n_jobs=-1, verbose=2, random_state=42)
bayes_gb.fit(X_train, y_train)
y_pred_bayes_gb = bayes_gb.best_estimator_.predict(X_test)
print(f"  • Mejores parámetros: {bayes_gb.best_params_}")
print(f"  • Mejor F1 (CV):      {bayes_gb.best_score_:.4f}")
print(f"  • F1 Test:            {f1_score(y_test, y_pred_bayes_gb):.4f}")
print(f"  • Accuracy Test:      {accuracy_score(y_test, y_pred_bayes_gb):.4f}")

# Regresión Logística
print("\n→ Bayesiana: Regresión Logística...")
bayes_lr = BayesSearchCV(modelo_lr, space_lr, cv=kfold, scoring='f1',
                         n_iter=20, optimizer_kwargs=optimizer_kwargs,
                         n_jobs=-1, verbose=2, random_state=42)
bayes_lr.fit(X_train, y_train)
y_pred_bayes_lr = bayes_lr.best_estimator_.predict(X_test)
print(f"  • Mejores parámetros: {bayes_lr.best_params_}")
print(f"  • Mejor F1 (CV):      {bayes_lr.best_score_:.4f}")
print(f"  • F1 Test:            {f1_score(y_test, y_pred_bayes_lr):.4f}")
print(f"  • Accuracy Test:      {accuracy_score(y_test, y_pred_bayes_lr):.4f}")

# SVM
print("\n→ Bayesiana: SVM...")
bayes_svm = BayesSearchCV(modelo_svm, space_svm, cv=kfold, scoring='f1',
                          n_iter=20, optimizer_kwargs=optimizer_kwargs,
                          n_jobs=-1, verbose=2, random_state=42)
bayes_svm.fit(X_train, y_train)
y_pred_bayes_svm = bayes_svm.best_estimator_.predict(X_test)
print(f"  • Mejores parámetros: {bayes_svm.best_params_}")
print(f"  • Mejor F1 (CV):      {bayes_svm.best_score_:.4f}")
print(f"  • F1 Test:            {f1_score(y_test, y_pred_bayes_svm):.4f}")
print(f"  • Accuracy Test:      {accuracy_score(y_test, y_pred_bayes_svm):.4f}")

# ─────────────────────────────────────────────────────────────────────────
# COMPARATIVA GRID VS BAYESIANA
# ─────────────────────────────────────────────────────────────────────────
print("\n" + "="*90)
print("COMPARATIVA GRIDSEARCH VS BAYESIANA")
print("="*90)

df_comparativa = pd.DataFrame({
    'Modelo': ['Gradient Boosting', 'Regresión Logística', 'SVM'],
    'Grid F1 CV': [grid_gb.best_score_, grid_lr.best_score_, grid_svm.best_score_],
    'Grid F1 Test': [f1_score(y_test, y_pred_gb), f1_score(y_test, y_pred_lr), f1_score(y_test, y_pred_svm)],
    'Bayes F1 CV': [bayes_gb.best_score_, bayes_lr.best_score_, bayes_svm.best_score_],
    'Bayes F1 Test': [f1_score(y_test, y_pred_bayes_gb), f1_score(y_test, y_pred_bayes_lr), f1_score(y_test, y_pred_bayes_svm)],
    'Bayes Accuracy Test': [accuracy_score(y_test, y_pred_bayes_gb), accuracy_score(y_test, y_pred_bayes_lr), accuracy_score(y_test, y_pred_bayes_svm)],
})

print(df_comparativa.to_string(index=False))

import pickle
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer

def preparar_datos(df):
    df = df.copy()

    # Convertir categóricas
    for col in df.select_dtypes(include='object').columns:
        df[col] = df[col].astype('category')

    # Convertir ceros a NaN y limpiar
    df.loc[df['RestingBP'] == 0, 'RestingBP'] = np.nan
    df['RestingBP'] = df['RestingBP'].fillna(df['RestingBP'].median())

    # Eliminar Cholesterol
    if 'Cholesterol' in df.columns:
        df = df.drop(columns=['Cholesterol'])

    # Dummies
    df = pd.get_dummies(df, columns=['Sex', 'ExerciseAngina'], drop_first=True, dtype=int)
    df = pd.get_dummies(df, columns=['ChestPainType', 'RestingECG', 'ST_Slope'], drop_first=False, dtype=int)

    # Eliminar ST_Slope_Flat (redundante)
    if 'ST_Slope_Flat' in df.columns:
        df = df.drop(columns=['ST_Slope_Flat'])

    # Ingeniería de características
    df['HR_Reserve'] = df['MaxHR'] - df['Age']
    df['AgeGroup'] = df['Age'].apply(lambda age: 0 if age < 45 else (1 if age < 60 else 2))
    df['BP_Category'] = df['RestingBP'].apply(lambda bp: 0 if bp < 120 else (1 if bp < 140 else 2)) if 'RestingBP' in df.columns else 0

    # Eliminar originales
    df = df.drop(columns=['Age', 'RestingBP'], errors='ignore')

    # Eliminar HeartDisease si viene en los datos
    if 'HeartDisease' in df.columns:
        df = df.drop(columns=['HeartDisease'])

    return df

# Crear pipeline final
pipeline_final = Pipeline([
    ('preparacion', FunctionTransformer(preparar_datos)),
    ('modelo', grid_gb.best_estimator_)
])

# Guardar
with open('modelo_final.pkl', 'wb') as f:
    pickle.dump(pipeline_final, f)

print("✓ Pipeline guardado en 'modelo_final.pkl'")
print("\nPasos del pipeline:")
for paso in pipeline_final.steps:
    print(f"  • {paso[0]}")